# Generated by Django 6.1 on 2026-09-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earning_app', '0002_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
